"""Initial migration

Revision ID: 3493557712a1
Revises: 
Create Date: 2025-01-10 19:19:16.873889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3493557712a1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('registry_code', sa.String(length=7), nullable=False),
    sa.Column('established_date', sa.Date(), nullable=False),
    sa.Column('total_capital', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registry_code')
    )
    op.create_table('shareholder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('personal_code', sa.String(length=11), nullable=True),
    sa.Column('registry_code', sa.String(length=7), nullable=True),
    sa.Column('share', sa.Integer(), nullable=False),
    sa.Column('is_founder', sa.Boolean(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shareholder')
    op.drop_table('company')
    # ### end Alembic commands ###
