"""Updated companyName

Revision ID: 652c66904468
Revises: 3493557712a1
Create Date: 2025-01-13 19:52:04.904602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '652c66904468'
down_revision = '3493557712a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shareholder', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_name', sa.String(length=100), nullable=True))
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shareholder', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('company_name')

    # ### end Alembic commands ###
